### ISSUE TITLE
has many bugs

### ISSUE THREAD

**Issue by lance-D** [WJsjtu/react-datepicker#2]
i fixed some bugs,but there is a bug that i cannot fixed.the days of month is wrong when you change 
the month

**Comment by lance-D** [comment]
as you see ,only 30 days when change 2017.1

**Comment by WJsjtu** [comment]
@bigdragon-D Well，Thx a lot for reporting the bugs and I‘m really sorry for my mistake. I have to admit that this project is not well coded because of my poor programming skills. The master branch will be used to publish the new date-picker component. This repository will publish a new branch for current version (version-1.0.0). And version-1.0.0 will be deprecated in a few days. I hope the new component will help you though there may be some changes in API or props. If there are still errors, please report it in issues and let me know them.

**Comment by WJsjtu** [comment]
@bigdragon-D I've checked the version-1.0.0 branch today morning  and found nothing wrong with 2017.1. Maybe the online demo was out-dated. If you stick on using v1.0.0, you can check again whether it works well or not. And the date calculating is coded mainly in `src/MonthObject.js` file.

**Comment by lance-D** [comment]
you are too modest,  i had fixed the bug ,thank you for your replay,yeah , i still use your old code ,cause i had modified your code a lot .
